# bundle exec jekyll serve --port 4001 --baseurl ''
title: ONDER â€” platform for creating, piloting and running new business models over the distributed energy market without a centralized billing system
email: hello@onder.tech
description: >- # this means to ignore newlines until "baseurl:"
  Commonwealth environment for digital energy business
baseurl: "/onder.tech" # the subpath of your site, e.g. /blog
url: "http://onder.tech" # the base hostname & protocol for your site, e.g. http://example.com



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  team:
  partners:
  sections:

url_medium: https://medium.com/%C3%B8nder
url_twitter: https://twitter.com/OnderPlatform
